version: "3.8"
services:
  #PHP Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network

  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ../frontend-code
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ../frontend-code:/var/www/html/
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3344:3306"
    environment:
      MYSQL_DATABASE: cms_land
      MYSQL_ROOT_PASSWORD: youngbach
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "3400:80"
    depends_on:
      - db
    networks:
      - app-network

  #Nginx Service
  webserver:
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network


volumes:
  dbdata:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge
